---
kind: pipeline
name: edge-x86

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: build
  pull: always
  image: alpinelinux/alpine-drone-ci:edge-x86
  commands:
  - linux32 build.sh
  environment:
    GH_TOKEN:
      from_secret: github_token

trigger:
  event:
  - pull_request

---
kind: pipeline
name: edge-x86_64

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: build
  pull: always
  image: alpinelinux/alpine-drone-ci:edge-x86_64
  commands:
  - build.sh
  environment:
    GH_TOKEN:
      from_secret: github_token

trigger:
  event:
  - pull_request

---
kind: pipeline
name: edge-aarch64

platform:
  os: linux
  arch: arm64

clone:
  disable: true

steps:
- name: build
  pull: always
  image: alpinelinux/alpine-drone-ci:edge-aarch64
  commands:
  - build.sh
  environment:
    GH_TOKEN:
      from_secret: github_token

trigger:
  event:
  - pull_request

---
kind: pipeline
name: edge-armhf

platform:
  os: linux
  arch: arm

clone:
  disable: true

steps:
- name: build
  pull: always
  image: alpinelinux/alpine-drone-ci:edge-armhf
  commands:
  - build.sh
  environment:
    GH_TOKEN:
      from_secret: github_token

trigger:
  event:
  - pull_request

---
kind: pipeline
name: edge-armv7

platform:
  os: linux
  arch: arm

clone:
  disable: true

steps:
- name: build
  pull: always
  image: alpinelinux/alpine-drone-ci:edge-armv7
  commands:
  - build.sh
  environment:
    GH_TOKEN:
      from_secret: github_token

trigger:
  event:
  - pull_request

...
